dist: bionic

language: python
python:
  - "3.7"

addons:
  apt:
    packages:
      - g++
      - freeglut3-dev

install:
  - python3 -m pip install -vvv -e .
  - python3 -m pip install -r requirements/test.txt
script: pytest || travis_terminate 1
