dist: xenial

language: python
python:
  - "3.7"

addons:
  apt:
    packages:
      - g++
      - freeglut3-dev

before_install:
  - pip3 install -r requirements-dev.txt

install: python3 setup.py build develop
script: python3 -c 'import kaa._kaa'
